# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IT-Tuts | Informatii utile din lumea internetului | Microjoburi
description: >- # this means to ignore newlines until "baseurl:"
   Pe platforma It-Tuts găsiti tutoriale, știri și alte informații utile despre lumea internetului. Învață cum să faci bani online, cum să iți faci un site sau ce sunt microjoburile.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

 
# Build settings
markdown: kramdown
theme: minima
permalink: /:categories/:title.html
disqus:
    shortname: it-tuts-ro
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
google_analytics: UA-86031208-3

plugins:
  - jekyll-get-json

jekyll_get_json:
  data: comments
  json: 'http://gsx2json.com/api?id=1c47kNUJtMi3Y3CM5YkqieCTkoFpTNHYHkOTOM4R8MWY&sheet=1'